name: notebook-env

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.13
  - jupyterlab
  - notebook
  - ipykernel
  - ipywidgets
  - numpy
  - pandas
  - matplotlib
  - scipy
  - pip
  - pandoc
